### ISSUE TITLE
[FEATURE] clear user decision for dev mode

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#10]
**Describe the solution you'd like**
When developing and implementing the CMP, you often apply consents or make service setting changes. Once you save or apply all consents, the dialog is gone and doesn't show up. This is intended for production and real users. For development process, it would be nice to reset the user decision and re-trigger the CMP popup. 

I would be nice to have a button or special function from `Usercentrics` obj. It would be also a safe way to only call the function depending of `__DEV__` constant.

**Describe alternatives you've considered**
At the moment we are changing service settings in UC Backend, but this is not a good practice, when our App with CMP gets live.

**Comment by uc-pedro** [comment]
Hello @fmacherey, thanks for opening this issue! 

We do have a method that can be used in this case, you can access it through `Usercentrics.reset()`.
Let me know if this method works for your expectations.

Thank you!

**Comment by fmacherey** [comment]
Yes, this works for us. Thanks for your help :)
