### ISSUE TITLE
[BUG] CMP doesn't show on older iPhones

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#12]
**Describe the bug**
It look like the CMP doesn't show up on older iPhones. We checked it with some Alert-boxes and the Usercentrics.status() never resolves. On iPhone 7 and 8, the promise seems to be not resolved always. On iPhone SE (2nd) and iPhone 12, the CMP show up as intend. 
We testet with several devices. On the listed older devices, sometimes to CMP is resovled, like 1 out of 5 times. We know this might be hard to trouble shoot or reproduce, it is also for us ;) 

I added the alert Alert `await Usercentrics.status()` and this is not showing up. I will test with another Alert, if we even reach `componentDidMount`.

Here is my class code, we are using:
```tsx
import React, { Component } from 'react';
import {
    Usercentrics,
    UsercentricsLoggerLevel,
    UsercentricsOptions,
    UsercentricsServiceConsent,
    UsercentricsUIOptions,
} from '@usercentrics/react-native-sdk';
import Config from 'react-native-config';
import { injectIntl, IntlShape } from 'react-intl';

interface Props {
    children: Element;
    intl: IntlShape;
}

interface State {
    consents: [UsercentricsServiceConsent] | null;
    ucReset: () => void;
}

export const ConsentContext = React.createContext<[UsercentricsServiceConsent] | null>(null);
export const DevelopemetConsentContext = React.createContext<null | (() => void)>(null);

class Consent extends Component<Props, State> {
    constructor(props: any) {
        super(props);
        const options = new UsercentricsOptions(Config.USERCENTRICS_ID);
        if (Config.EXPERIMENTAL_FEATURES) {
            options.loggerLevel = UsercentricsLoggerLevel.debug;
        }
        options.defaultLanguage = this.props.intl.locale;
        Usercentrics.configure(options);
        this.state = { consents: null, ucReset: Usercentrics.reset };
    }

    async componentDidMount() {
        const status = await Usercentrics.status();
        if (status.shouldShowCMP) {
            this.showCMP(false).then();
        } else {
            this.applyConsents(status.consents);
        }
    }

    async showCMP(showCloseButton: boolean) {
        const options = new UsercentricsUIOptions(showCloseButton);
        const response = await Usercentrics.showCMP(options);
        console.log('showCMP', response.consents);
        this.setState({ consents: response.consents });
    }

    applyConsents(consents: [UsercentricsServiceConsent]) {
        console.log('applyConsents', consents);
        this.setState({ consents });
    }

    render() {
        return (
            <ConsentContext.Provider value={this.state.consents}>
                {Config.EXPERIMENTAL_FEATURES ? (
                    <DevelopemetConsentContext.Provider value={this.state.ucReset}>
                        {this.props.children}
                    </DevelopemetConsentContext.Provider>
                ) : (
                    this.props.children
                )}
            </ConsentContext.Provider>
        );
    }
}

export default injectIntl(Consent);

```

**usercentrics/react-native branch/commit**
v2.0.2

**Comment by fmacherey** [comment]
@uc-pedro i figured out that `componentDidMount` is called but the promise is not resolved.

**Comment by uc-pedro** [comment]
Hello @fmacherey I'll take look into this issue, we know that there is a known issue related to old devices where they don't have background color on the header, but this was fixed already and will be released soon.

**Comment by fmacherey** [comment]
Hey @uc-pedro,
 
do you have a timeframe for this? We have to implement the cmp in our app in the next days/weeks. Otherwise we have to find a workaround e.g. with Browser-UI and a Webview, but this is obviously a lot more overhead in handling the consents.

**Comment by uc-pedro** [comment]
Hello @fmacherey, we have already started to investigate this issue today

**Comment by fmacherey** [comment]
@uc-pedro 
We testet several devices, and older iPhones didn't show up the cmp. I used an iPhone 8 with  iOS 15.1. Maybe you can update your iOS too? Maybe this is releated to the new Safari/Webkit to be more strict with cookies? 

I added several Alerts to the class component shown above. Before the await was reached, but then the promise was not awaited. I can try to add a catch block, to figure out more.

**Comment by fmacherey** [comment]
i added a catch() to `await Usercentrics.status()` and this also didn't come up with the Alert box. So it looks like the promise is still pending.

**Comment by uc-pedro** [comment]
I figured out here what might be causing the issue, do you have any other screen before this one where you can place the configure logic and in this screen place just the Usercentrics.status promise?

I'm investigating why this is happening but in a nutshell, it seems that the status promise is not being called because the configure method has not finished yet.

**Comment by fmacherey** [comment]
I am not able to push the configure higher up in the Application, as it is almost the top-level (with in the IntlProvider). 

So configure has to be async, but is not in constructor?  If that helps, I can try to split the configuring into a top component, which does only the configure process in an useEffect. Or do you have a better solution from your side?

**Comment by uc-pedro** [comment]
I'm looking into our core now to see if it's possible to fix from there, so you would not need to do anything

**Comment by fmacherey** [comment]
Thanks, that would be nice :)

**Comment by uc-pedro** [comment]
Hello @fmacherey I've fixed the issue, in a few mins we will be pushing a new version so you can check it out!

**Comment by fmacherey** [comment]
Yes, that works. Thanks :)

**Comment by fmacherey** [comment]
The dialog now works on older devices, but there is a possible new bug. When I am developing with a simulator, and reload the metro dev server, the app crashes within the native code: 
![image](https://user-images.githubusercontent.com/72257175/140889220-cf7c1d49-18c5-485a-8e76-bfd1b5d77af3.png)

**Comment by uc-pedro** [comment]
Oh, I will be fixing this now. Sorry about that!

**Comment by uc-pedro** [comment]
hello @fmacherey, I think that now everything is fine! Thanks for your help with this issue!

**Comment by fmacherey** [comment]
Yes, it look now its working as expected :) thank you for your help 🚀
