### ISSUE TITLE
[FEATURE] add testing mocks for jest

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#13]
**Is your feature request related to a problem? Please describe.**
When testing a Component with jest, jest complains about the import of the ESM Module. It would be nice to have test-mocks bundled with this package, to be able to test Components which use usercentrics.

**Comment by uc-pedro** [comment]
Hello @fmacherey, thanks for the suggestion, we will implement something like this for sure. 
For now, we have in our project some unit tests which mocks our native module using jest 
https://github.com/Usercentrics/react-native-sdk/blob/master/src/__tests__/index.test.ts

**Comment by fmacherey** [comment]
@uc-pedro thanks for your reply. I will have a look onto it next week.

**Comment by fmacherey** [comment]
For now, it is enough to mock the `Usercentrics` export like this: 

```js
jest.mock('@usercentrics/react-native-sdk', () => ({
    Usercentrics: jest.fn(),
}));
```
