### ISSUE TITLE
[BUG/FEATURE] showSecondLayer

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#17]
**Describe the bug**
What is the way to show the second layer of Usercentrics? We want to open the vendor list from our apps' about screen. Is there an intended way of this? In the browser-ui there is `showSecondLayer()` method. 

Not sure if this is a bug or missing feature or a missing documentation. 

**usercentrics/react-native branch/commit**
v2.0.3-rc-2

**Comment by uc-pedro** [comment]
Hello @fmacherey, right now we don't have this feature implemented, but is on the roadmap already.

**Comment by fmacherey** [comment]
Do you have a timeframe on this?

**Comment by uc-pedro** [comment]
Not yet, but as soon we have it I'll update this issue.
