### ISSUE TITLE
[BUG] Higher deployment target required

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#20]
**Describe the bug**
I updated to 2.0.3 but now getting the following error from `pod install`:
```sh
[...]
[!] CocoaPods could not find compatible versions for pod "UsercentricsUI":
  In snapshot (Podfile.lock):
    UsercentricsUI (= 2.0.2)

  In Podfile:
    react-native-usercentrics (from `../node_modules/@usercentrics/react-native-sdk`) was resolved to 2.0.3, which depends on
      UsercentricsUI (= 2.0.3)

Specs satisfying the `UsercentricsUI (= 2.0.2), UsercentricsUI (= 2.0.3)` dependency were found, but they required a higher minimum deployment target.
```
I also tried to adjust the deployment target in my project to iOS 12 and also inside die usercentrics specs in xcode, but that seems to be still not enough.

**usercentrics/react-native branch/commit**
v2.0.2

**Comment by uc-pedro** [comment]
Hello @fmacherey , you need to navigate to your iOS folder, then run `pod deintegrate `, after that delete any reference to Podfile.lock, then run `pod install `again

**Comment by fmacherey** [comment]
Nevermind, `pod install --repo-update` fixed the pods.
