### ISSUE TITLE
[BUG] Logo is not displayed on second layer on IOS

### ISSUE THREAD

**Issue by DominikHinc** [Usercentrics/react-native-sdk#29]
**Describe the bug**
After setting up the new 2.2.1 version of the SDK everything seems to work fine, except for the logo on the second layer on IOS.

**To Reproduce**
1. Install new SDK version
2. Invoke the show second layer function:
`Usercentrics.showSecondLayer({
    showCloseButton: showCloseButton,
    bannerSettings: new BannerSettings(
      new UsercentricsLogo('logo', Image.resolveAssetSource(require('app/assets/images/logo.png'))),
      new UsercentricsFont(
        `${typography.primary}-${fontWeightMap[typography.primary].regular}`,
        typography.fontSizeDefault,
      ),
    ),
 })`
3. The logo is not displayed.
The same behaviour occurs for going from first layer to the second one. (And on the first layer the logo is visible):
`Usercentrics.showFirstLayer(
    new FirstLayerOptions(UsercentricsLayout.popupCenter, bannerSettings, {
      headerImage: {
        image: new UsercentricsLogo(
          'logo',
          Image.resolveAssetSource(require('app/assets/images/logo.png')),
        ),
        isHidden: false,
        isExtended: false,
        alignment: SectionAlignment.center,
      },
    }),
  )`

**Expected behavior**
The logo should be displayed on the second layer.

**Comment by uc-pedro** [comment]
Hello @DominikHinc, thanks for opening this issue! 
We are working already on a fix for this issue and it should be addressed in the next release
