### ISSUE TITLE
[BUG] Brand logo is not visible inside the app 

### ISSUE THREAD

**Issue by adeem** [Usercentrics/react-native-sdk#33]
**Describe the bug**
We are using latest library 2.3.0 and starting to use Banner API v2 (https://docs.usercentrics.com/cmp_in_app_sdk/latest/collect_consent/present_cmp/). This looks great but inside our app, we do not see our branding logo. 
In CMP v2, we added SVG file path of our brand logo. On our website, its working fine

**To Reproduce**
1. Go to https://admin.usercentrics.eu/#/v2/appearance/
2. Add SVG file path under logo section
3. Publish your changes
4. Inside the app, you do not see any logo being shown (in first layer and also not shown in second layer)

**Expected behavior**
SVG branded logo should be shown inside the app

**Screenshots**
![IMG_2285](https://user-images.githubusercontent.com/68442/162883243-1279fcd7-b3f8-46c1-be1d-68d335f41bc3.PNG)

**Comment by uc-noack** [comment]
Hi @adeem 

Thank you for your feedback.
We currently do not support [SVGs being passed via the URL](https://docs.usercentrics.com/cmp_in_app_sdk/latest/collect_consent/customize_cmp/#logo) in the Admin Interface. (We will address this in an upcoming release)
A solution we provide to solve this is to pass an[ image directly to the SDK] via our Programmatic Customization API.(https://docs.usercentrics.com/cmp_in_app_sdk/latest/collect_consent/customize_cmp/#bannersettings).

Please let us know if that solves your issues.
Best

Franco

**Comment by adeem** [comment]
At the end we added PNG
