### ISSUE TITLE
[HOW TO] How to inject user session in react native webview?

### ISSUE THREAD

**Issue by hkar19** [Usercentrics/react-native-sdk#34]
Hello, Thank you for this amazing SDK.

Currentlly i am working in an app that is using webview capabilty, which requires session injection to prevent UC Prompts reappear in the webview.

I am using this stack:
- `react-native@0.67.1`
- `react-native-webview@9.0.2`

I am able to inject user session data in iOS by following [this guide](https://docs.usercentrics.com/cmp_in_app_sdk/latest/features/webview-continuity/#webview-user-session-continuity), where i have done:

```ts
injectUCSessionData = () => {
    const sessionData = this.props.userSessionData;
    return `
    window.UC_UI_USER_SESSION_DATA = ${sessionData};
    `;
  };
  
  // later in webview
  <Webview
    injectedJavaScriptBeforeContentLoaded={this.injectUCSessionData()}
  // ...other props
  />
```

but in android, the prompt keep reappearing in the webview. 

What is the proper way to inject session data in Android? what idea was wanted to be achieved when we want to inject this user session data?

**Comment by adeem** [comment]
I think you have to do 2 things

first: In your Inject method, return true as well  return 
```
return ` window.UC_UI_USER_SESSION_DATA = ${sessionData}; 
true; `
```
We also added `{}` as well in the return

second: Add sharedCookiesEnabled to true for webview
```
<Webview
    injectedJavaScriptBeforeContentLoaded={this.injectUCSessionData()}
  sharedCookiesEnabled=true
  />
```

**Comment by hkar19** [comment]
Actually i have tried added `true` at the end of my injected script, and added `sharedCookiesEnabled` as well to Webview props, but the UC prompts keep reappears in Android.

i am intrigued by 

> We also added `{}` as well in the return

what did you mean by that?

**Comment by adeem** [comment]
`return {${injectCode} true;}`

where inject code is `window.UC_UI_USER_SESSION_DATA = ${usercentricsSession};`

and usercentricsSession == JSON.stringify(usercentricsSession || {})
and userCentricsSession was retreieved from == payload.usercentricsSession

I do have one hint which helped me a lot. Are you passing the information as String or Object?

**Comment by hkar19** [comment]
btw, it was the problem of my `react-native-webview`. i just realized i run `react-native-webview@9.4.0` and i apply this diff.
[as this comment i made](https://github.com/react-native-webview/react-native-webview/issues/1609#issuecomment-1109665318)

my problem was solved :)

**Comment by hkar19** [comment]
as for the `sessionData`,
i passed the `this.props.userSessionData` was gotten from `Usercentrics.getUserSessionData()` that i store in redux (as that was async function, but i need it ready before the page is loading).

I think `Usercentrics.getUserSessionData()` returns a JSON

**Comment by adeem** [comment]
So you can close this bug? I are with you that we are using updated version of webview

**Comment by hkar19** [comment]
yes, i can close this bug. The way i handled the injected script is fine, what is not there was no handler in the Native Webview component.

thank you
