### ISSUE TITLE
Android Crash version 2.6.1 "ui thread execution is required" [BUG]

### ISSUE THREAD

**Issue by timh1004** [Usercentrics/react-native-sdk#44]
**Describe the bug**
After installing version 2.6.1 I'm getting an error when calling `Usercentrics.showFirstLayer(options)` on Android and the App crashes.
The error says "ui thread execution is required" for Usercentrics.isReady.
Version 2.6.0 is working fine.

**Comment by userCTest** [comment]
hey @timh1004 
thanks for reporting the issue.
We'll have a look and let you know as soon as we have any updates.

**Comment by userCTest** [comment]
Hi @timh1004 
just wanted to let you know that we have managed to replicate the issue on our side (using the example app contained in the SDK) and will investigate what the issue is to try and provide a fix. As soon as we have any updates, we'll let you know.
Have a good weekend! 
Rui

**Comment by uc-leo** [comment]
@timh1004 2.7.0 is out, can you verify that this problem is fixed? thanks!

**Comment by uc-leo** [comment]
@timh1004 2.7.0 is out, can you verify that this problem is fixed? thanks!
