### ISSUE TITLE
[BUG] - Android is not saving settings when pressing "Save Settings" from the firstLayer

### ISSUE THREAD

**Issue by ehcg** [Usercentrics/react-native-sdk#46]
**Describe the bug**
on iOS everything works. On Android, Save Settings from the `firstLayer` makes the dialog go away, but the next time the app is launched I get
> [USERCENTRICS][DEBUG] SHOW_CMP cause: [TCF] This user has not yet provided consent (not even on GDPR services)
on the logs, and the dialog is shown again

**To Reproduce**
1. CMP is shown on an Android device
2. Click on "Save Settings"
3. the CMP goes away, but the next time the app is launched, the CMP is shown.
4. Log shows:
> > [USERCENTRICS][DEBUG] SHOW_CMP cause: [TCF] This user has not yet provided consent (not even on GDPR services)

**Expected behavior**
CMP settings are saved.

**Comment by userCTest** [comment]
Hi Eduardo,

I tried to reproduce the issue with the example app contained in the SDK and with a test tcf settingsId but I am unable to replicate it. 
Could you try reproducing it using our example?  

Cheers,
Rui
