### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by rweligamage** [Usercentrics/react-native-sdk#5]
Issue: can't use the WebView with user session.

Reason: getUserSessionData() is not exposed for RN yet.

It would be really helpful if you could expose this also.

**Comment by uc-pedro** [comment]
Hello @rweligamage!

Thanks for opening this issue, we are working on this feature and it will be released soon, probably this week.

Please feel free to provide any feedback that could be useful for us to improve it.
