### ISSUE TITLE
[PATCH] `getUserSessionData` method should `await RNUsercentricsModule.isReady()`.

### ISSUE THREAD

**Issue by hkar19** [Usercentrics/react-native-sdk#53]
**Describe the bug**
I encountered many bugs from appcenter analytic where:
```bash
com.usercentrics.sdk.errors.NotReadyException: Usercentrics is not ready, please ensure to invoke the shared instance inside 'Usercentrics.isReady'
```

i noticed that in this (already `async`) method of `getUserSessionData` does not await for `RNUsercentricsModule.isReady()` where every other method is already `await`ing.

here is my patch suggestion:
`@usercentrics+react-native-sdk+2.3.0.patch`
```diff
diff --git a/node_modules/@usercentrics/react-native-sdk/lib/Usercentrics.js b/node_modules/@usercentrics/react-native-sdk/lib/Usercentrics.js
index 170fa66..25c2b21 100644
--- a/node_modules/@usercentrics/react-native-sdk/lib/Usercentrics.js
+++ b/node_modules/@usercentrics/react-native-sdk/lib/Usercentrics.js
@@ -35,7 +35,8 @@ export const Usercentrics = {
         await RNUsercentricsModule.isReady();
         return RNUsercentricsModule.getCMPData();
     },
-    getUserSessionData: () => {
+    getUserSessionData: async () => {
+        await RNUsercentricsModule.isReady();
         return RNUsercentricsModule.getUserSessionData();
     },
     getCCPAData: async () => {

```

I concur this method should also `await`ing the `RNUsercentricsModule.isReady()`:
- this method is already returning a Promise
- i personally `await`ed on app start, but somehow on some devices it already call `getUserSessionData` before `await`ing the `RNUsercentricsModule.isReady()`

**usercentrics/react-native branch/commit**
- Your fork/commit: 2.3.0

**Comment by uc-nfdz** [comment]
@hkar19 Nice catch! Thank you very much, we will include it in the next upcoming release.
