### ISSUE TITLE
[BUG] essential toggle buttons are are able to toggle

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#6]
**Describe the bug**
As seen in the attached screenshot below, the user is able to click the essential category. This also happens for services which are marked as essential.
The button has disabled style, but the onClick event is still attached. I think this is only a UI issue. 

**Screenshots**
![image](https://user-images.githubusercontent.com/72257175/140392123-6f2ab885-5eb0-4526-b346-cb157dec7458.png)
![image](https://user-images.githubusercontent.com/72257175/140392138-49902139-cb11-4a65-a5b9-a41093ee2b1e.png)

**usercentrics/react-native branch/commit**
- v2.0.3-rc2

**Comment by fmacherey** [comment]
Edit: this happens only for iOS. Android is working as intended.

**Comment by uc-pedro** [comment]
Hello @fmacherey thanks for opening this issue! 
We have already fixed that and it will be released soon. 

Thank you!

**Comment by uc-pedro** [comment]
@fmacherey yes, it's just a visual bug
