### ISSUE TITLE
[BUG] Logo is not displayed on first/second layer on Android (release)

### ISSUE THREAD

**Issue by mihaf70** [Usercentrics/react-native-sdk#62]
Logo is not displayed neither on first layer, nor on second. Issue is reproducible only on android (release mode). Config is done in the same way as in the examples. Logo is a regular .png file.

First layer setup and show:
![Screenshot 2023-02-01 at 10 09 53](https://user-images.githubusercontent.com/72543203/216000085-025afc48-9f3e-4699-ada3-af502971458a.png)

Second layer setup and show:
![Screenshot 2023-02-01 at 10 10 36](https://user-images.githubusercontent.com/72543203/216000196-bd7504f8-0030-4ad3-9d11-ca79663a4822.png)

**Comment by userCTest** [comment]
Hey @mihaf70 

we have an example on how to set up the logo [here](https://github.com/Usercentrics/react-native-sdk/blob/master/example/src/screens/CustomizationExamples.tsx#L98). Maybe you can check that out and see if that works for you.

Cheers,
Rui

**Comment by mihaf70** [comment]
@userCTest it's done in the same way :c

**Comment by userCTest** [comment]
@mihaf70 can you please try 
`BannerLogo("logo.png", Image.resolveAssetSource(require('app/assets/images/logo.png')`
on creating the Banner logo and see if that works?

**Comment by mihaf70** [comment]
@userCTest  I was trying to do it that way but it also didn't work

**Comment by userCTest** [comment]
@mihaf70 I tried 

`logo: new BannerLogo(
        'logo.png',
        Image.resolveAssetSource(require('./assets/images/logo.png')),
      )`
in a sample app and it works:
![image](https://user-images.githubusercontent.com/67687938/216065218-7880efd9-b528-4bc0-b7d6-e841dfd90e49.png)

Can you try that?
Cheers,
Rui

**Comment by mihaf70** [comment]
@userCTest No, I don't have any errors. In general it's working on android (debug), iOS (debug/release), the problem occurs only on android release so I'm not sure if the problem is in a path itself.

**Comment by mihaf70** [comment]
And image is bundled correctly because I'm able to display it regularly in <Image/> component so it's really weird.

**Comment by userCTest** [comment]
@mihaf70 I have managed to replicate the issue and created an internal ticket for our devs to have a look into it. 
As soon as we have any updates, I'll let you know.

Best,
Rui

**Comment by uc-leo** [comment]
@mihaf70 PR is opened 🎉 

https://github.com/Usercentrics/react-native-sdk/pull/63

**Comment by uc-leo** [comment]
Released! @mihaf70 if anything goes wrong you can re-open this issue. Thanks
