### ISSUE TITLE
[BUG] Failing to compile on android

### ISSUE THREAD

**Issue by joleb** [Usercentrics/react-native-sdk#81]
**Describe the bug**
After updating to the latest react native version (0.72) and trying to run android or compile it for production, it fails with an error.

**To Reproduce**
Run android debug or try to compile android for release

**Expected behavior**
Compilation does not fail

**Screenshots**
![image](https://github.com/Usercentrics/react-native-sdk/assets/38313415/0a489d4a-8069-406b-a3a0-843a9650fd2a)
```
* What went wrong:
Execution failed for task ':usercentrics_react-native-sdk:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```
**Additional context**
react-native: 0.72

**Comment by joleb** [comment]
Repo to recreate: https://github.com/joleb/usercentrics-android-error/tree/0.72.0

**Comment by userCTest** [comment]
Hey @joleb 

have you tried changing the java version you are targeting in your compliance options of the app build.gradle file:
![Screenshot 2023-06-26 at 10 07 29](https://github.com/Usercentrics/react-native-sdk/assets/67687938/d6ee5099-6f9a-4fb1-b473-a97b1ac55a61)

Cheers,
Rui

**Comment by joleb** [comment]
Hey @userCTest ,
I tried it multiple times with different variants, even trying to add to kotlin options, which almost always lead to the same result of not being able to compile it.
![image](https://github.com/Usercentrics/react-native-sdk/assets/38313415/3f608e55-033f-4015-a02c-a2d86f2411c2)

**Comment by userCTest** [comment]
Hey @joleb ,

so you still get the same message if you set the compileOptions as below?
![image](https://github.com/Usercentrics/react-native-sdk/assets/67687938/3422f9c4-6934-41f2-81f9-6ad4b9b686f8)

**Comment by userCTest** [comment]
Hey @joleb ,

I being doing some testing on your repo and found the issue I think. You need to  change the grade version to < 8, e.g. 7.5 
![Screenshot 2023-06-27 at 11 43 01](https://github.com/Usercentrics/react-native-sdk/assets/67687938/5a3bcf9c-e25d-48a7-905d-9d74a0cb406f)
That coupled with the previous change of adding 
```
compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
```
to the android block of the app build.gradle made the app compile without issues. Seems to be an issue with the gradle version 8+ that we will investigate.

Let me know if this helps.

**Comment by userCTest** [comment]
Great news @joleb, thanks for the info.
Glad to help 😄 

I've opened an internal ticket to see what might be the issue with newer gradle versions.
Will let you know once we have news.

Cheers

**Comment by userCTest** [comment]
Hey @joleb 

just wanted to let you know that the latest version of the SDK now supports gradle 8+
Have a look and let us know if you find any issues.

Cheers,
Rui

**Comment by joleb** [comment]
Hello @uc-rreis , the same error occurs when trying to use the latest react native version. It seems like that the latest gradle versions are no longer supported: https://github.com/Usercentrics/react-native-sdk/commit/140e45cc172cc614bc202b2c64eeb6ca8c804877

**Comment by uc-leo** [comment]
hi @joleb , we haven't changed anything on this matter, so it's kinda odd that this is happening... can you provide more details, please?

**Comment by csath** [comment]
I cannot build the Android app with the latest React native and usercentrics versions. I get the following error. 

```java
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':usercentrics_react-native-sdk:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 1.8) JVM target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

I'm using following versions:
```json
"@usercentrics/react-native-sdk": "2.11.3",
"react-native": "0.73.2"
```

This has been a blocker for me in upgrading my project to the latest react-native version. 😞 

I tried setting different `compileOptions` and `kolinOptions` in my project, but nothing helped. The same error was thrown. 
Then I had a look on usercentrics react native sdk `android/build.gradle` and noticed jvmTarget is set to `'1.8'`.  In react-native 0.73, java 17 is a [requirement now](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#other-breaking-changes) and according to docs,[ Kotlin `1.8.0` can generate classes with a bytecode version corresponding to JVM 19](https://kotlinlang.org/docs/whatsnew18.html#kotlin-jvm). So I removed this `jvmTarget = '1.8'` and I believe `sourceCompatibility` and `targetCompatibility` can still stay with `JavaVersion.VERSION_1_8`. I can get the project working with this patch and the usercentric features are working so far. 

Here is the patch I created. 
```gradle
diff --git a/node_modules/@usercentrics/react-native-sdk/android/build.gradle b/node_modules/@usercentrics/react-native-sdk/android/build.gradle
index 64ebf4b..1aac99b 100644
--- a/node_modules/@usercentrics/react-native-sdk/android/build.gradle
+++ b/node_modules/@usercentrics/react-native-sdk/android/build.gradle
@@ -34,10 +34,6 @@ android {
         targetCompatibility JavaVersion.VERSION_1_8
     }
 
-    kotlinOptions {
-        jvmTarget = '1.8'
-    }
-
     sourceSets {
         main.java.srcDirs += 'src/main/kotlin'
     }

```

I'm not a native Android developer, so I have little knowledge of this area. I'm not sure if this is the proper fix or what issues this might bring in. 

@uc-leo Do you know any other ways I can try to get this working with react native-version 0.73? or any information regarding a timeline of a new version of usercentrics will be out supporting react-native 0.73?

**Comment by huschu** [comment]
We are also blocked by this, so any further updates would be much appreciated.

**Comment by joleb** [comment]
Hey @uc-leo , basically the same behaviour @csath described.

**Comment by uc-rreis** [comment]
Hey guys,

I'll try having a look, will let you know as soon as I have any updates.

Cheers,
Rui

**Comment by uc-rreis** [comment]
Hey Guys, 

just wanted to give you a heads-up that we will be looking into fixing the issue.
As soon as we have any updates, we'll let you know.

Cheers,
Rui

**Comment by csath** [comment]
> Hey Guys,
> 
> just wanted to give you a heads-up that we will be looking into fixing the issue. As soon as we have any updates, we'll let you know.
> 
> Cheers, Rui

Thanks a lot. I have already rolled out our app to 100% users with the above patch I mentioned and it works without any problems. 
I'm waiting for a updated version of this library to get rid of this patch. 🤞

**Comment by uc-leo** [comment]
thank you all for the effort and time invested on this issue 🤘

PR: #108
