### ISSUE TITLE
[BUG] applyAll when restart the app without user interaction

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#9]
**Describe the bug**
It looks like the package is not correctly working when the CMP open, but the user is not interacting with this. When you open the app again (hard restart), the CMP is not showing up. With logging we figured out, that all consents are now accepted. So `await Usercentrics.status()` `shouldShowCMP` property seems to be not true.

**To Reproduce**
1. open the app
2. CMP dialog is shown
3. close app via iOS mulit tasking view
4. reopen app
5. CMP doesn't show up and all consents are set to true.

**Expected behavior**
CMP should open again and not accepting without explicit user decision.

**usercentrics/react-native branch/commit**
v0.0.3, iOS, Android not checked yet

**Comment by uc-pedro** [comment]
Hello @fmacherey we have already fixed this issue and we are going to push that out soon. 

Thank you!
