### ISSUE TITLE
[BUG] Cannot read property 'configure' of null

### ISSUE THREAD

**Issue by mirzayevkamal** [Usercentrics/react-native-sdk#94]
**I can not init the library.  When I try**
  ```
useEffect(() => {
    let options: UsercentricsOptions = { settingsId: 'Yi9N3aXia' };
    options.loggerLevel = UsercentricsLoggerLevel.debug;
    Usercentrics.configure(options);

    initializeUsercentrics();
  }, []);
```
I get error saying: Cannot read property 'configure' of null

When I log 'Usercentrics' I get all the data but can not call configure method.

Versions:
 ```
   "@usercentrics/react-native-sdk": "^2.9.0",
   "react": "18.2.0",
   "react-native": "^0.71.0",
    kotlinVersion = "1.7.0"
```
<img width="311" alt="Screenshot 2023-10-25 at 13 09 23" src="https://github.com/Usercentrics/react-native-sdk/assets/49615672/ba8cddda-2306-47ce-9734-baf02bfde9f0">

**Comment by uc-piotukh** [comment]
Hi @mirzayevkamal,
Sounds like the SDK has not finished initialising and something in the `initializeUsercentrics();` function relies on its status.
Could you please let me know what is in the `initializeUsercentrics();`? That would help a lot!

Thanks!
Aliaksandra Piotukh
