### ISSUE TITLE
[BUG] SSL error when installing/updating pods

### ISSUE THREAD

**Issue by bitfabrikken** [Usercentrics/react-native-sdk#99]
**Describe the bug**
Now that TCF2.2 is coming and latest version of this module is 2.10.0, I wanted to upgrade from 2.8.3 to 2.8.4.

But no matter which version I try to install, I get SSL errors.
Taking the URLs and manually putting them in a browser, also gives SSL errors.
So not sure if it's a problem with your hosting, the files or something else.
Just thought you should be aware of it, as right now, it appears no one can install/update your module.

**To Reproduce**
1. Your module in package.json:
```
  "dependencies": {
    "@usercentrics/react-native-sdk": "2.8.4",
  },
```
2. Execute yarn with "yarn", which installs according to package.json
3. cd ios ; pod update
Output:
```
Installing Usercentrics (2.8.4)

[!] Error installing Usercentrics
[!] /usr/bin/curl -f -L -o /var/folders/y9/4xtsq4qn0tlbxbgszwmmp3dc0000gn/T/d20231124-19254-mehmz6/file.zip https://bitbucket.org/usercentricscode/usercentrics-spm-sdk/downloads/Usercentrics-2.8.4.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bbuseruploads.s3.amazonaws.com:443 
```
If you use the URL elsewhere, https://bitbucket.org/usercentricscode/usercentrics-spm-sdk/downloads/Usercentrics-2.8.4.xcframework.zip , you will see it also fails, such as on different devices and networks.

Various SSL errors from various programs and browsers:
- Error code: PR_END_OF_FILE_ERROR
- SSL_ERROR_SYSCALL
- GnuTLS: The TLS connection was non-properly terminated.

Google Chrome can download the file. Firefox and Safari can't.

**Expected behavior**
Able to update/install pods.

**Comment by uc-rreis** [comment]
Hey @bitfabrikken,

I just tested on Safari and could download the file.

Also tried the curl command slightly modified 
```
/usr/bin/curl -f -L -o Usercentrics/file.zip https://bitbucket.org/usercentricscode/usercentrics-spm-sdk/downloads/Usercentrics-2.8.4.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'
```
and it also worked:
![Screenshot 2023-11-24 at 12 26 14](https://github.com/Usercentrics/react-native-sdk/assets/67687938/e9431190-1477-4c70-994f-67662265b427)

Have you tried using 
```
pod install --repo-update
```
instead of the simple pod install?

**Comment by bitfabrikken** [comment]
Safari doesn't work either here.
Your curl cmd output:
```
/usr/bin/curl -f -L -o Usercentrics/file.zip https://bitbucket.org/usercentricscode/usercentrics-spm-sdk/downloads/Usercentrics-2.8.4.xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bbuseruploads.s3.amazonaws.com:443 
```

So same error. 

wget works now though, although the first reponse gives 302, then tries another url.

I did try pod repo update previously yes, several times.

Maybe it's an issue with AWS. Would make sense, as it might be just a couple of their servers with some bad config, out of many - would explain why it's working for you anyway.

I've tried 3 different internet connections and it happens on all of them, so perhaps related to geo?

**Comment by bitfabrikken** [comment]
Maybe adding some credibility to the geo suspicion: Your curl cmd works for me on a server in Germany. All the issues I have are on internet connections in Denmark. Have no VPN access to test further though, but you could perhaps VPN to Denmark.

**Comment by uc-rreis** [comment]
Tried the curl command from several locations (India, Germany, Portugal, California), and always worked. 

Are you behind some proxy or something like that which could block the request in any way?

**Comment by uc-rreis** [comment]
Still works for Denmark I'm afraid:
![Screenshot 2023-11-24 at 12 50 53](https://github.com/Usercentrics/react-native-sdk/assets/67687938/08fb271a-214d-4642-8543-bda52ebc397b)

**Comment by uc-rreis** [comment]
similar error [here](https://github.com/Homebrew/brew/issues/4436#issuecomment-403194892) it seems, curl config. 
Could, it be this?

**Comment by bitfabrikken** [comment]
> Tried the curl command from several locations (India, Germany, Portugal, California), and always worked.
> 
> Are you behind some proxy or something like that which could block the request in any way?

No proxy no, pod update/install always worked without a hitch. And I've made no changes to my local networking in years. 
I just noticed it works on the other network I tested on, cellular, but it did not work ~20 mins ago.
So only place it's not working now, is my local network, by the looks of it.

I'll hop on cellular and install, then investigate if it's still a problem monday.

**Comment by uc-rreis** [comment]
OK, cool Dan. 
Let us know how it pans out.

Enjoy the weekend!

**Comment by bitfabrikken** [comment]
> similar error [here](https://github.com/Homebrew/brew/issues/4436#issuecomment-403194892) it seems, curl config issue. Could it be this?

I don't think so (tried HOMEBREW_FORCE_BREWED_CURL from the link, no luck)
I also get the curl errors it on various linux boxes too.
It's also not just curl, it's various browsers and wget (although that seems to work again now).

**Comment by bitfabrikken** [comment]
@uc-rreis it's still failing with those SSL errors. It's very odd. Next step is to contact the ISP I guess.

**Comment by uc-rreis** [comment]
Hey @bitfabrikken 

really strange indeed. Don't really see any other way forward tbh.
Please keep us updated.
